name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [ "develop", "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: your-eb-app-name
          environment_name: your-eb-env-name
          region: ${{ secrets.AWS_REGION }}
          version_label: v-${{ github.run_number }}
          deployment_package: target/myapp-0.0.1-SNAPSHOT.jar